services:
    grafana:
        build: grafana/
        ports: 
            - "3000:3000"
        volumes:
            - grafana:/var/lib/grafana
            - ./grafana/provisioning:/etc/grafana/provisioning
        environment:
            - GF_INSTALL_PLUGINS=grafana-clock-panel
    prometheusdb:
        build: prometheusdb/
        ports:
            - "9090:9090"
        volumes:
            - ./prometheusdb/config:/etc/prometheus/
            - prometheusdb:/prometheus
    prometheus-proxy:
        build: prometheus-proxy/
        volumes:
            - ./prometheus-proxy/config:/opt/config/snmp_exporter
    node1:
        build: snmp/
        volumes:
            - ./snmp/node1/config:/etc/snmp
            - ./snmp/scripts:/usr/sbin/scripts
    node2:
        build: snmp/
        volumes:
            - ./snmp/node2/config:/etc/snmp
            - ./snmp/scripts:/usr/sbin/scripts            
    node3:
        build: snmp/
        volumes:
            - ./snmp/node3/config:/etc/snmp
            - ./snmp/scripts:/usr/sbin/scripts   
    node4:
        build: snmp/
        volumes:
            - ./snmp/node4/config:/etc/snmp
            - ./snmp/scripts:/usr/sbin/scripts            
volumes: 
  prometheusdb:
  grafana:
