# A scrape configuration scraping a Node Exporter and the Prometheus server
# itself.
# https://prometheus.io/docs/prometheus/latest/configuration/configuration/
scrape_configs:
  # Scrape Prometheus itself every 10 seconds.
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']